#!/usr/bin/env bash
# This script displays a phrase 9 times and a different one at 10

COUNTER=1
while [ $COUNTER -lt 10 ]
do
	if [ $COUNTER -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	fi
	echo "Best School"
	((COUNTER++))
done
