#!/usr/bin/env bash
# This script displays a phrase 9 times and a different one at 10

COUNTER=0
while [ $COUNTER -ne 10 ]
do
	if [ $COUNTER -eq 9 ]
	then
		echo "Hi"
		break
	fi
	echo "Best School"
	((COUNTER++))
done
