#!/usr/bin/env bash
# This script displays a phrase 9 times and a different one at 10

COUNTER=1
while [ $COUNTER -ne 11 ]
do
	if [ $COUNTER -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((COUNTER++))
done
