#!/usr/bin/env bash
# Displays different text at 4th, 8th and other iterations

COUNTER=0
while [ $COUNTER -ne 10 ]
do
	if [ $COUNTER -eq 3 ]
	then
		echo "bad luck"
	elif [ $COUNTER -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((COUNTER++))
done
